### ISSUE TITLE
"Bounce back" and "drag" no longer work in 1.03 and 1.02

### ISSUE THREAD

**Issue by hay** [tomlongo/Flickable.js#1]
When looking at the demos, they have a very nice 'drag' and 'bounce back' animation, so it really feels native. However, in 1.03 and 1.02 that no longer happens and you need to make the gesture first before any animation happens.

**Comment by tomlongo** [comment]
Oh crap I'm such an idiot! I somehow managed to delete a chunk of code that stopped the touch and drag thing from working in webkit. 

I've just committed 1.0.4 which should fix the issue -- let me know if you still experience the problem. 

Thanks for letting me know. No idea how I missed it. «

**Comment by hay** [comment]
Thanks for the super quick response and commit. Works like a charm. Thanks again!

**Comment by tomlongo** [comment]
No worries, thanks for letting me know!
