### ISSUE TITLE
Link to demo sample not working

### ISSUE THREAD

**Issue by Ruffio** [tomlongo/Flickable.js#13]
Hi.

The links to the samples are broken :-(

Kindly regards

**Comment by jasonfb** [comment]
wayback has the three demos:

http://web.archive.org/web/20120904031912/http://blog.kojo.com.au/demos/flickable/demo1.html

http://web.archive.org/web/20121006080049/http://blog.kojo.com.au/demos/flickable/demo2.html

http://web.archive.org/web/20130701132852/http://labs.kojo.com.au/demos/flickable/demo3.html
