### ISSUE TITLE
Feature request: Initial segment option

### ISSUE THREAD

**Issue by apaatsio** [tomlongo/Flickable.js#6]
I would like to see an option to set the initial segment to something else than 0. 
For example, to initially show the third segment I could do it like this:

``` javascript
$('#flickable').flickable({ segments: 5, initialSegment: 2 });
```

Currently the only way I know how to accomplish this is:

``` javascript
$('#flickable').flickable({ segments: 5 });
$('#flickable').flickable('segment', 2);
```

**Comment by pballada** [comment]
+1 to this request.

**Comment by gibo** [comment]
+1

**Comment by apaatsio** [comment]
Closing as stale.
